typography_spectrum: 0.8187674621585757
color:
  saturation: 0.235768
  brandStrength: 0.2341798837296665
  lightness: 0.4300025
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.694286
layout_spectrum: 0.2443609
name: Rain Light Fade
navigation:
  - name: About Us
    id: a3f7ff0c-d560-4926-8831-a227ec6a0d2d
    type: content
  - name: Music
    id: 2c0df73a-88b1-4aea-b574-20b765419260
    type: content
  - name: Videos
    id: dfa8fe9a-aa27-401c-b240-a4a716fb7041
    type: content
  - name: Press
    id: 964d6c8c-ba1b-4e03-a0ed-d4757d5b2383
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Heavy | Dark | Beautiful
description: Rock n' Roll from Seattle
