title: Heavy | Dark | Beautiful
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.235768
  brandStrength: 0.4677766
  lightness: 0.4300025
  brandColors:
    - '#010101'
    - '#363837'
    - '#919191'
    - '#595B5A'
    - '#C1BFB3'
  rhythmicContrast: 0.694286
typography_spectrum: 0.1519871
description: Rock n' Roll from Seattle
navigation:
  - name: About Us
    id: a3f7ff0c-d560-4926-8831-a227ec6a0d2d
    type: content
  - name: Music
    id: 2c0df73a-88b1-4aea-b574-20b765419260
    type: content
  - name: Videos
    id: dfa8fe9a-aa27-401c-b240-a4a716fb7041
    type: content
  - name: Press
    id: 964d6c8c-ba1b-4e03-a0ed-d4757d5b2383
    type: content
layout_spectrum: 0.5719656
name: Rain Light Fade
