typography_spectrum: 0.8187674621585757
color:
  saturation: 0.235768
  brandStrength: 0.2341798837296665
  lightness: 0.4300025
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  rhythmicContrast: 0.694286
layout_spectrum: 0.2443609
name: Rain Light Fade
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Heavy | Dark | Beautiful
